# Generated by Django 4.2 on 2025-04-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbRabbit', models.IntegerField(default=0)),
                ('nbCage', models.IntegerField(default=0)),
                ('funds', models.FloatField(default=0.0)),
                ('foodQuantity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('inGameRaising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevage.elevage')),
            ],
        ),
    ]
