# Generated by Django 4.2 on 2025-05-07 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Elevage Sans nom', max_length=100)),
                ('nb_males', models.PositiveBigIntegerField(default=1)),
                ('nb_femelles', models.PositiveBigIntegerField(default=1)),
                ('quantite_nourriture', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('nb_cages', models.PositiveBigIntegerField(default=1)),
                ('solde', models.IntegerField(default=0)),
                ('nbTurn', models.PositiveBigIntegerField(default=0)),
                ('nbSoldRabbits', models.PositiveBigIntegerField(default=0)),
                ('moneyMade', models.BigIntegerField(default=0)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elevages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('PRESENT', 'Présent'), ('VENDU', 'Vendu'), ('MORT', 'Mort'), ('GRAVIDE', 'Gravide')], max_length=20)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individus', to='elevage.elevage')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodPrice', models.IntegerField(default=10)),
                ('cagePrice', models.IntegerField(default=100)),
                ('rabbitSalePrice', models.IntegerField(default=50)),
                ('medecinePrice', models.IntegerField(default=20)),
                ('consumptionFood1Month', models.FloatField(default=0)),
                ('consumptionFood2Month', models.FloatField(default=0.1)),
                ('consumptionFood3Month', models.FloatField(default=0.25)),
                ('maxRabys', models.IntegerField(default=4)),
                ('maxPerCage', models.IntegerField(default=6)),
                ('maxAge', models.IntegerField(default=25)),
                ('minAgeGravide', models.IntegerField(default=6)),
                ('maxAgeGravide', models.IntegerField(default=24)),
                ('gestation', models.IntegerField(default=1)),
                ('maxPossiblePerCage', models.IntegerField(default=10)),
                ('probMortContamine', models.FloatField(default=0.2)),
                ('probGuerison', models.FloatField(default=0.5)),
                ('probContaminaison', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('SANTE', 'En santé'), ('GUERISON', 'Guérison'), ('CONTAMINE', 'Contamination'), ('MORT', 'Mort')], default='SANTE', max_length=15)),
                ('individu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='elevage.individu')),
            ],
        ),
    ]
