# Generated by Django 4.2 on 2025-04-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='player',
        ),
    ]
