# Generated by Django 4.2 on 2025-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0002_elevage_username_delete_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevage',
            old_name='nbCage',
            new_name='nb_cages',
        ),
        migrations.RenameField(
            model_name='elevage',
            old_name='nbRabbit',
            new_name='nb_femelles',
        ),
        migrations.RemoveField(
            model_name='elevage',
            name='foodQuantity',
        ),
        migrations.RemoveField(
            model_name='elevage',
            name='funds',
        ),
        migrations.RemoveField(
            model_name='elevage',
            name='username',
        ),
        migrations.AddField(
            model_name='elevage',
            name='nb_males',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elevage',
            name='nom',
            field=models.CharField(default='Partie sans nom', max_length=100),
        ),
        migrations.AddField(
            model_name='elevage',
            name='quantite_nourriture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elevage',
            name='solde',
            field=models.IntegerField(default=0),
        ),
    ]
