# Generated by Django 4.2 on 2025-04-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0003_rename_nbcage_elevage_nb_cages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('PRESENT', 'Présent'), ('VENDU', 'Vendu'), ('MORT', 'Mort'), ('GRAVIDE', 'Gravide')], max_length=20)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individus', to='elevage.elevage')),
            ],
        ),
    ]
