# Generated by Django 4.2 on 2025-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0004_individu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodPrice', models.IntegerField(default=10)),
                ('cagePrice', models.IntegerField(default=100)),
                ('rabbitSalePrice', models.IntegerField(default=50)),
                ('consumptionNourriture1Month', models.IntegerField(default=0)),
                ('consumptionNourriture2Month', models.IntegerField(default=100)),
                ('consumptionNourriture3Month', models.IntegerField(default=250)),
                ('maxRabys', models.IntegerField(default=4)),
                ('maxPerCage', models.IntegerField(default=6)),
                ('minAgeGravide', models.IntegerField(default=6)),
                ('maxAgeGravide', models.IntegerField(default=48)),
                ('gestation', models.IntegerField(default=1)),
            ],
        ),
    ]
