# Generated by Django 4.2 on 2025-04-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0005_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='consumptionNourriture1Month',
            new_name='consumptionFood1Month',
        ),
        migrations.RenameField(
            model_name='rules',
            old_name='consumptionNourriture2Month',
            new_name='consumptionFood2Month',
        ),
        migrations.RenameField(
            model_name='rules',
            old_name='consumptionNourriture3Month',
            new_name='consumptionFood3Month',
        ),
    ]
