# Generated by Django 4.2 on 2025-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0006_rename_consumptionnourriture1month_rules_consumptionfood1month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='maxAge',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='rules',
            name='maxAgeGravide',
            field=models.IntegerField(default=24),
        ),
    ]
