# Generated by Django 4.2 on 2025-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0007_rules_maxage_alter_rules_maxagegravide'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='moneyMade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elevage',
            name='nbSoldRabbits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elevage',
            name='nbTurn',
            field=models.IntegerField(default=0),
        ),
    ]
