# Generated by Django 4.2 on 2025-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0008_elevage_moneymade_elevage_nbsoldrabbits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevage',
            name='moneyMade',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nbSoldRabbits',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nbTurn',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nb_cages',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nb_femelles',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nb_males',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='quantite_nourriture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rules',
            name='consumptionFood1Month',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rules',
            name='consumptionFood2Month',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='rules',
            name='consumptionFood3Month',
            field=models.FloatField(default=0.25),
        ),
    ]
