# Generated by Django 5.1.7 on 2025-04-28 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0008_elevage_moneymade_elevage_nbsoldrabbits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='utilisateur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='elevages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevage',
            name='moneyMade',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nbSoldRabbits',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nbTurn',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nb_cages',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nb_femelles',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nb_males',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='quantite_nourriture',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rules',
            name='consumptionFood1Month',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rules',
            name='consumptionFood2Month',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='rules',
            name='consumptionFood3Month',
            field=models.FloatField(default=0.25),
        ),
    ]
