# Generated by Django 4.2.9 on 2025-04-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elevage", "0008_elevage_moneymade_elevage_nbsoldrabbits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="maxPossiblePerCage",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="moneyMade",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="nbSoldRabbits",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="nbTurn",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="nb_cages",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="nb_femelles",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="nb_males",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="quantite_nourriture",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="rules",
            name="consumptionFood1Month",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="rules",
            name="consumptionFood2Month",
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name="rules",
            name="consumptionFood3Month",
            field=models.FloatField(default=0.25),
        ),
        migrations.CreateModel(
            name="Sante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("SANTE", "En santé"),
                            ("GUERISON", "Guérison"),
                            ("CONTAMINE", "Contamination"),
                            ("MORT", "Mort"),
                        ],
                        default="SANTE",
                        max_length=15,
                    ),
                ),
                (
                    "individu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sante",
                        to="elevage.individu",
                    ),
                ),
            ],
        ),
    ]
