# Generated by Django 4.2.20 on 2025-05-05 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevage', '0009_elevage_utilisateur_alter_elevage_moneymade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevage',
            name='nom',
            field=models.CharField(default='Elevage Sans nom', max_length=100),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elevages', to=settings.AUTH_USER_MODEL),
        ),
    ]
