# Generated by Django 4.2.9 on 2025-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevage", "0009_rules_maxpossiblepercage_alter_elevage_moneymade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="probMortContamine",
            field=models.FloatField(default=0.2),
        ),
    ]
