# Generated by Django 4.2 on 2025-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "elevage",
            "0009_alter_elevage_moneymade_alter_elevage_nbsoldrabbits_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="elevage",
            name="history",
            field=models.JSONField(default=list),
        ),
    ]
