# Generated by Django 4.2 on 2025-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevage", "0010_elevage_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevage",
            name="quantite_nourriture",
            field=models.FloatField(default=0),
        ),
    ]
