# Generated by Django 4.2 on 2025-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevage", "0010_rules_probmortcontamine"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="medecinePrice",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="rules",
            name="probGuerison",
            field=models.FloatField(default=0.5),
        ),
    ]
