# Generated by Django 4.2 on 2025-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevage", "0011_rules_medecineprice_rules_probguerison"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="probContaminaison",
            field=models.FloatField(default=0.1),
        ),
    ]
