# Generated by Django 4.2.20 on 2025-05-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0011_elevage_pdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevage',
            name='pdp',
            field=models.CharField(choices=[('https://lemeilleurpourmonlapin.fr/wp-content/uploads/2022/01/lapin-belier-nain.jpg', 'jaune'), ('https://lh3.googleusercontent.com/proxy/7s3lshDlxtWy15XXy5cB1_EISdBDe0i4Sj5rqYCjSmS5XmlPpTPABCSX71UL7bWy8Iv92y-G4mVJjjL5GPB-6AKRSIDcetWg_GbcYdovo7k9', 'bleu'), ('https://lh4.googleusercontent.com/proxy/5ZHyOawMBFglp8U_yezB7QRM5Ab1blvz3qKi1odPlHd5efZgFvwaSdKCgM5ngoe1l2aERXxZGrHiQc-WUJhHY_Znq_Esdox95g2aIlVUQyPMRw', 'rouge')], default=['https://img.freepik.com/vecteurs-libre/souris-heureuse-mangeant-du-fromage_1308-174159.jpg'], max_length=255),
        ),
    ]
