# Generated by Django 4.2.20 on 2025-05-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0012_alter_elevage_pdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevage',
            name='pdp',
        ),
    ]
