# Generated by Django 4.2 on 2025-05-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "elevage",
            "0009_alter_elevage_moneymade_alter_elevage_nbsoldrabbits_and_more",
        ),
        ("elevage", "0012_rules_probcontaminaison"),
    ]

    operations = []
