# Generated by Django 4.2 on 2025-05-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0013_merge_20250505_1634'),
        ('elevage', '0015_alter_userprofile_profile_picture'),
    ]

    operations = [
    ]
